version = 1

test_patterns = [
  "worker/test/**/*.spec.ts",
  "app/cypress/e2e/**/*.cy.js"
]

exclude_patterns = [".github/**"]

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  plugins = ["react"]
