version: '3.8'
services:
  dynamodb:
    image: amazon/dynamodb-local:latest
    ports:
      - "8100:8000"
  init-dynamodb:
    image: amazon/aws-cli:latest
    command: "dynamodb --endpoint-url http://dynamodb:8000 create-table --region eu-west-1 --table-name vh7 --key-schema AttributeName=id,KeyType=HASH --attribute-definitions AttributeName=id,AttributeType=S --provisioned-throughput ReadCapacityUnits=1,WriteCapacityUnits=1 > /dev/null"
    environment:
      - "AWS_ACCESS_KEY_ID=DUMMYIDEXAMPLE"
      - "AWS_SECRET_ACCESS_KEY=DUMMYEXAMPLEKEY"
    depends_on:
      dynamodb:
        condition: service_started
  minio:
    image: minio/minio:latest
    command: "server /data -console-address ':9001'"
    environment:
      - "MINIO_DOMAIN=localhost"
    ports:
      - "9000:9000"
      - "9001:9001"
  init-minio:
    image: amazon/aws-cli:latest
    command: "s3api --endpoint-url http://minio:9000 create-bucket --bucket vh7-uploads > /dev/null"
    environment:
      - "AWS_ACCESS_KEY_ID=minioadmin"
      - "AWS_SECRET_ACCESS_KEY=minioadmin"
    depends_on:
      minio:
        condition: service_started
