/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/shorten": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Create a new shortened URL */
        post: operations["postApiShorten"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/paste": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Create a new shared code snippet */
        post: operations["postApiPaste"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Upload a new shared file */
        post: operations["postApiUpload"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/event": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Create a new shared calendar event */
        post: operations["postApiEvent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/info/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Retrieve information on the given short link item */
        get: operations["getApiInfoById"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/delete/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** @description Delete a short link item with it's delete token */
        delete: operations["deleteApiDeleteById"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: never;
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    postApiShorten: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    /**
                     * Format: uri
                     * @example https://example.com
                     */
                    url: string;
                } & {
                    /**
                     * @description A date for when the item will expire. The value must be 1 year at the most (31 days for files). Set to `null` to disable expiry of this item (except for files).
                     * @default 2025-10-21T14:19:54.432Z
                     */
                    expires?: string | null;
                    /** @description An optional string that allows you to later delete the item before it expires (see the `/api/delete/{id}` route). */
                    deleteToken?: string | null;
                };
            };
        };
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        id: string;
                        url: string;
                        createdAt: string;
                        updatedAt: string;
                        expiresAt: string | null;
                        /** @constant */
                        type: "url";
                    };
                };
            };
        };
    };
    postApiPaste: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    /** @example def add(a, b):
                     *         return a + b */
                    code: string;
                    /**
                     * @description If provided, the code will syntax highlighted for this language.
                     * @example python
                     */
                    language?: ("markup" | "bash" | "clike" | "c" | "cpp" | "css" | "css-extras" | "javascript" | "jsx" | "js-extras" | "js-templates" | "coffeescript" | "diff" | "git" | "go" | "graphql" | "markup-templating" | "handlebars" | "json" | "less" | "makefile" | "markdown" | "objectivec" | "ocaml" | "python" | "reason" | "sass" | "scss" | "sql" | "stylus" | "tsx" | "typescript" | "wasm" | "yaml") | null;
                } & {
                    /**
                     * @description A date for when the item will expire. The value must be 1 year at the most (31 days for files). Set to `null` to disable expiry of this item (except for files).
                     * @default 2025-10-21T14:19:54.434Z
                     */
                    expires?: string | null;
                    /** @description An optional string that allows you to later delete the item before it expires (see the `/api/delete/{id}` route). */
                    deleteToken?: string | null;
                };
            };
        };
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        id: string;
                        code: string;
                        language: string | null;
                        createdAt: string;
                        updatedAt: string;
                        expiresAt: string | null;
                        /** @constant */
                        type: "paste";
                    };
                };
            };
        };
    };
    postApiUpload: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "multipart/form-data": {
                    /** Format: binary */
                    file: string;
                } & {
                    /**
                     * @description A date for when the item will expire. The value must be 1 year at the most (31 days for files). Set to `null` to disable expiry of this item (except for files).
                     * @default 2025-10-21T14:19:54.435Z
                     */
                    expires?: string | null;
                    /** @description An optional string that allows you to later delete the item before it expires (see the `/api/delete/{id}` route). */
                    deleteToken?: string | null;
                } & {
                    /**
                     * @description A date for when the item will expire. The value must be 1 year at the most (31 days for files). Set to `null` to disable expiry of this item (except for files).
                     * @default 2025-10-21T14:19:54.435Z
                     */
                    expires?: string | null;
                    /** @description An optional string that allows you to later delete the item before it expires (see the `/api/delete/{id}` route). */
                    deleteToken?: string | null;
                };
            };
        };
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        id: string;
                        filename: string;
                        size: number;
                        hash: string;
                        createdAt: string;
                        updatedAt: string;
                        expiresAt: string | null;
                        /** @constant */
                        type: "upload";
                    };
                };
            };
        };
    };
    postApiEvent: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    /** @example My event */
                    title: string;
                    description?: string | null;
                    location?: string | null;
                    startDate: string;
                    endDate?: string | null;
                    /** @default false */
                    allDay?: boolean;
                } & {
                    /**
                     * @description A date for when the item will expire. The value must be 1 year at the most (31 days for files). Set to `null` to disable expiry of this item (except for files).
                     * @default 2025-10-21T14:19:54.436Z
                     */
                    expires?: string | null;
                    /** @description An optional string that allows you to later delete the item before it expires (see the `/api/delete/{id}` route). */
                    deleteToken?: string | null;
                };
            };
        };
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        id: string;
                        title: string;
                        description: string | null;
                        location: string | null;
                        startDate: string;
                        endDate: string | null;
                        allDay: boolean;
                        createdAt: string;
                        updatedAt: string;
                        expiresAt: string | null;
                        /** @constant */
                        type: "event";
                    };
                };
            };
        };
    };
    getApiInfoById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        id: string;
                        url: string;
                        createdAt: string;
                        updatedAt: string;
                        expiresAt: string | null;
                        /** @constant */
                        type: "url";
                    } | {
                        id: string;
                        code: string;
                        language: string | null;
                        createdAt: string;
                        updatedAt: string;
                        expiresAt: string | null;
                        /** @constant */
                        type: "paste";
                    } | {
                        id: string;
                        filename: string;
                        size: number;
                        hash: string;
                        createdAt: string;
                        updatedAt: string;
                        expiresAt: string | null;
                        /** @constant */
                        type: "upload";
                    } | {
                        id: string;
                        title: string;
                        description: string | null;
                        location: string | null;
                        startDate: string;
                        endDate: string | null;
                        allDay: boolean;
                        createdAt: string;
                        updatedAt: string;
                        expiresAt: string | null;
                        /** @constant */
                        type: "event";
                    };
                };
            };
        };
    };
    deleteApiDeleteById: {
        parameters: {
            query: {
                deleteToken: string;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        deleted: string;
                        status: number;
                    };
                };
            };
        };
    };
}
