name = "vh7"
type = "javascript"
compatibility_date = "2021-12-06"
account_id = ""
workers_dev = true
route = ""
zone_id = ""

# [secrets]
# AWS_ACCESS_KEY_ID
# AWS_SECRET_ACCESS_KEY

[vars]
AWS_S3_BUCKET = "uploads"
AWS_ENDPOINT_URL = "https://gateway.eu1.storjshare.io"
AWS_DEFAULT_REGION = ""
VH7_ENV = "production"
DYNAMODB_TABLE = "vh7"
DYNAMODB_DEFAULT_REGION = "eu-west-1"
DYNAMODB_ENDPOINT_URL = "https://dynamodb.eu-west-1.amazonaws.com"

[miniflare]
kv_persist = true
env_path = ".env"

[build]
command = "yarn install && yarn run build"
[build.upload]
format = "service-worker"
