name = "vh7"
compatibility_date = "2021-12-06"
workers_dev = true
main = "src/index.ts"

[vars]
VH7_ENV = "development"
VH7_ADMIN_TOKEN = "keyboardcat"

[[d1_databases]]
binding = "DB"
database_name = "vh7-development"
database_id = "87904197-0107-411a-a030-be6ed70f8ff7"
migrations_dir = "migrations"

[[r2_buckets]]
binding = "UPLOADS"
bucket_name = "vh7-uploads-development"

[env.production.vars]
VH7_ENV = "production"

[[env.production.d1_databases]]
binding = "DB"
database_name = "vh7"
database_id = "8248b645-7133-4795-a343-e9273706f77c"
migrations_dir = "migrations"

[[env.production.r2_buckets]]
binding = "UPLOADS"
bucket_name = "vh7-uploads-production"

[[env.production.routes]]
pattern = "vh7.uk/*"
zone_name = "vh7.uk"

[[env.production.routes]]
pattern = "www.vh7.uk/*"
zone_name = "vh7.uk"
