name = "vh7"
type = "javascript"
compatibility_date = "2021-12-06"
account_id = ""
workers_dev = true
route = ""
zone_id = ""

kv_namespaces = [
  { binding = "VH7", id = "52cdf6272a704bc991b5b6e5b98421fe", preview_id = "" }
]

# [secrets]
# AWS_ACCESS_KEY_ID
# AWS_SECRET_ACCESS_KEY

[vars]
AWS_S3_BUCKET = "uploads"
AWS_ENDPOINT_URL = "gateway.eu1.storjshare.io"
AWS_DEFAULT_REGION = ""
VH7_ENV = "production"

[miniflare]
kv_persist = true
env_path = ".env"

[build]
command = "yarn install && yarn run build"
[build.upload]
format = "service-worker"
