name = "vh7"
compatibility_date = "2021-12-06"
workers_dev = true
main = "src/index.ts"

# [secrets]
# S3_ACCESS_KEY_ID
# S3_SECRET_ACCESS_KEY

[vars]
S3_ACCESS_KEY_ID = "minioadmin"
S3_SECRET_ACCESS_KEY = "minioadmin"
S3_REGION = "eu-west-1"
S3_ENDPOINT_URL = "http://localhost:9000"
S3_BUCKET = "vh7-uploads"
VH7_ENV = "development"

[[d1_databases]]
binding = "DB" # i.e. available in your Worker on env.DB
database_name = "vh7"
database_id = "8248b645-7133-4795-a343-e9273706f77c"
preview_database_id = "c7e738c7-0b24-4c49-a3db-695e8658c01c"
migrations_dir = "migrations"
