name: Cypress E2E
on:
  - push
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm install
      - name: Migrate database
        run: pnpm dlx wrangler d1 migrations apply DB --local
      - name: Build frontend
        working-directory: ./app
        run: pnpm build
        env:
          VITE_SENTRY_DSN: ${{ secrets.APP_SENTRY_DSN }}
      - name: Run app
        run: |
          pnpm dlx wrangler dev > ./worker.log 2>&1 &
          pnpm dlx wait-on --timeout 30000 http-get://localhost:8787
      - name: Cypress run
        working-directory: ./app
        run: pnpm cypress run --e2e --record true --config baseUrl=http://localhost:8787
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
      - name: Print Logs
        if: ${{ failure() }}
        run: cat ./worker.log
