name: Cypress E2E
on:
  - push
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    services:
      dynamodb:
        image: amazon/dynamodb-local:latest
        ports:
          - 8000:8000
      minio:
        image: bitnami/minio:latest
        env:
          MINIO_ROOT_USER: minio
          MINIO_ROOT_PASSWORD: minio123
        ports:
          - 9000:9000
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2.1.2
        with:
          node-version: 16
      - name: Get cache directory
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - name: Cache node_modules
        uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Create DynamoDB Table
        uses: giboow/action-aws-cli@v1
        with:
          args: dynamodb --endpoint-url http://dynamodb:8000 create-table --region eu-west-1 --table-name vh7 --key-schema AttributeName=id,KeyType=HASH --attribute-definitions AttributeName=id,AttributeType=S --provisioned-throughput ReadCapacityUnits=1,WriteCapacityUnits=1
        env:
          AWS_ACCESS_KEY_ID: testid
          AWS_SECRET_ACCESS_KEY: testkey
      - name: Create S3 Bucket
        uses: giboow/action-aws-cli@v1
        with:
          args: s3api --endpoint-url http://minio:9000 create-bucket --bucket vh7-uploads
        env:
          AWS_ACCESS_KEY_ID: minio
          AWS_SECRET_ACCESS_KEY: minio123
      - name: Install dependencies
        run: yarn install --dev
      - name: Run API
        working-directory: ./worker
        run: |
          env > .env
          yarn run preview > ../worker.log 2>&1 &
          npx -y wait-on --timeout 30000 http-get://localhost:8787
        env:
          AWS_ACCESS_KEY_ID: minio
          AWS_SECRET_ACCESS_KEY: minio123
          AWS_DEFAULT_REGION: eu-west-1
          AWS_ENDPOINT_URL: http://localhost:9000
          AWS_S3_BUCKET: vh7-uploads
          DYNAMODB_ACCESS_KEY_ID: testid
          DYNAMODB_SECRET_ACCESS_KEY: testkey
          DYNAMODB_TABLE: vh7
          DYNAMODB_ENDPOINT_URL: http://localhost:8000
          VH7_ENV: testing
      - name: Build & Run App
        working-directory: ./app
        run: |
          yarn run build --mode testing
          yarn run preview --mode testing > ../app.log 2>&1 &
          # npx -y wait-on --timeout 30000 http://localhost:3000
      - name: Cypress run
        working-directory: ./app
        run: yarn run cypress run --e2e --record true
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
      - name: Print Logs
        if: ${{ failure() }}
        run: |
          cat ./worker.log
          cat ./app.log
